---
- name: Install Splunk Enterprise on Ubuntu 22.04
  hosts: all
  become: yes

  vars:
    splunk_version: "9.1.0"  # Replace with the latest version
    splunk_package_url: "https://download.splunk.com/products/splunk/releases/9.3.0/linux/splunk-9.3.0-51ccf43db5bd-linux-2.6-amd64.deb"
    splunk_home: "/opt/splunk"
    splunk_user: "splunk"
    splunk_password: "yourpassword"  # Replace with your desired password

  tasks:

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - wget
        - tar

    - name: Download Splunk Enterprise
      get_url:
        url: "{{ splunk_package_url }}"
        dest: "/tmp/splunk.deb"

    - name: Install Splunk Enterprise
      apt:
        deb: "/tmp/splunk.deb"
        state: present

    - name: Create Splunk user
      user:
        name: "{{ splunk_user }}"
        create_home: no
        shell: /bin/bash

    - name: Start Splunk service
      command: "{{ splunk_home }}/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd {{ splunk_password }}"
      args:
        creates: "{{ splunk_home }}/etc/splunk-started"

    - name: Enable Splunk to start on boot
      command: "{{ splunk_home }}/bin/splunk enable boot-start -user {{ splunk_user }}"

    - name: Restart Splunk service
      command: "{{ splunk_home }}/bin/splunk restart"
